insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ridiculus mus', 994, '976860869', 'cgraham0@yolasite.com', 'Christine', 'Graham');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ligula nec sem', 35, '686738117', 'rrobertson1@economist.com', 'Ronald', 'Robertson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ipsum aliquam', 60, '903133465', 'jowens2@meetup.com', 'Justin', 'Owens');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quisque', 948, '601028969', 'jbrown3@goodreads.com', 'Jose', 'Brown');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('integer ac leo', 874, '741335581', 'pbailey4@blogspot.com', 'Pamela', 'Bailey');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam nec dui', 324, '913414633', 'nboyd5@typepad.com', 'Nicole', 'Boyd');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('orci luctus', 464, '967422085', 'sbowman6@51.la', 'Sandra', 'Bowman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('luctus', 423, '030874164', 'lprice7@slashdot.org', 'Lillian', 'Price');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nam', 656, '567531504', 'aruiz8@wisc.edu', 'Amanda', 'Ruiz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eu felis', 468, '451578048', 'bboyd9@ft.com', 'Bruce', 'Boyd');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('erat volutpat in', 859, '795241624', 'ghuntera@quantcast.com', 'Gregory', 'Hunter');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('integer non velit', 605, '887616653', 'crobertsonb@liveinternet.ru', 'Catherine', 'Robertson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam turpis adipiscing', 771, '858776419', 'rsimsc@example.com', 'Robin', 'Sims');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sagittis nam congue', 137, '986104045', 'twillisd@sphinn.com', 'Teresa', 'Willis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in', 863, '514045999', 'ldavise@tripod.com', 'Lois', 'Davis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vulputate', 5, '825675306', 'chartf@alexa.com', 'Catherine', 'Hart');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('tempus semper est', 135, '514181748', 'jmasong@blinklist.com', 'Jonathan', 'Mason');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dolor morbi vel', 47, '328602225', 'jharperh@ibm.com', 'Janet', 'Harper');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('rhoncus sed', 431, '788773439', 'cschmidti@smh.com.au', 'Christina', 'Schmidt');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quisque arcu', 576, '746369645', 'jpricej@edublogs.org', 'Joseph', 'Price');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sapien dignissim', 135, '972851167', 'npricek@google.com.hk', 'Norma', 'Price');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nullam', 448, '923842718', 'jpalmerl@foxnews.com', 'John', 'Palmer');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('montes nascetur ridiculus', 351, '613676574', 'spowellm@addtoany.com', 'Shawn', 'Powell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('porta', 430, '542345158', 'alanen@goo.gl', 'Angela', 'Lane');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mattis egestas metus', 249, '462788475', 'mbakero@ow.ly', 'Mary', 'Baker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sapien iaculis congue', 897, '940175326', 'darmstrongp@pcworld.com', 'Denise', 'Armstrong');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lorem ipsum', 142, '262790127', 'mbakerq@weather.com', 'Margaret', 'Baker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pellentesque viverra pede', 518, '293941003', 'cstoner@multiply.com', 'Carlos', 'Stone');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in hac habitasse', 133, '624815399', 'rphillipss@rediff.com', 'Richard', 'Phillips');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mi', 574, '848224087', 'kgarrettt@w3.org', 'Katherine', 'Garrett');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('natoque', 394, '019381279', 'ctayloru@ebay.co.uk', 'Carolyn', 'Taylor');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla neque libero', 429, '688691812', 'lmoralesv@archive.org', 'Lori', 'Morales');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quisque ut', 644, '796006286', 'trussellw@webmd.com', 'Teresa', 'Russell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nisi', 372, '312313709', 'tdunnx@japanpost.jp', 'Todd', 'Dunn');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dapibus duis', 377, '617075189', 'vreidy@dedecms.com', 'Virginia', 'Reid');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('luctus rutrum', 185, '764992966', 'hperezz@ifeng.com', 'Heather', 'Perez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lacinia', 443, '010749368', 'shanson10@wsj.com', 'Sarah', 'Hanson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('augue luctus tincidunt', 316, '499270131', 'tperry11@jalbum.net', 'Teresa', 'Perry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eget', 775, '353889210', 'cjordan12@csmonitor.com', 'Christina', 'Jordan');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('neque sapien', 399, '510397669', 'drivera13@diigo.com', 'David', 'Rivera');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('viverra eget congue', 990, '164239105', 'dtorres14@simplemachines.org', 'Douglas', 'Torres');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('venenatis', 157, '791014819', 'smorgan15@simplemachines.org', 'Stephen', 'Morgan');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('blandit non interdum', 13, '965567365', 'klane16@vinaora.com', 'Kelly', 'Lane');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('viverra', 121, '560177481', 'nperez17@qq.com', 'Nicole', 'Perez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam pharetra', 379, '175650675', 'dhenderson18@rakuten.co.jp', 'Dorothy', 'Henderson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('cursus urna', 191, '276956221', 'dhanson19@cdc.gov', 'Douglas', 'Hanson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('libero nullam', 673, '342175160', 'wwells1a@weebly.com', 'Willie', 'Wells');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ligula', 637, '126519263', 'kwells1b@mayoclinic.com', 'Kevin', 'Wells');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('a', 696, '936720259', 'areid1c@flavors.me', 'Angela', 'Reid');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sed tincidunt', 58, '032679554', 'jknight1d@edublogs.org', 'Jessica', 'Knight');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('consequat', 874, '098236329', 'rruiz1e@seesaa.net', 'Ruth', 'Ruiz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('erat quisque erat', 783, '977709751', 'aphillips1f@wp.com', 'Amanda', 'Phillips');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet consectetuer', 348, '171165953', 'amoore1g@wiley.com', 'Alan', 'Moore');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('faucibus', 534, '667320859', 'tturner1h@issuu.com', 'Todd', 'Turner');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('convallis morbi odio', 606, '818148462', 'lramos1i@technorati.com', 'Lisa', 'Ramos');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mi', 568, '708336224', 'kcoleman1j@macromedia.com', 'Kenneth', 'Coleman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('tellus', 699, '315600625', 'agordon1k@yandex.ru', 'Adam', 'Gordon');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('molestie', 796, '317561593', 'bscott1l@utexas.edu', 'Billy', 'Scott');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ac', 173, '916795919', 'jandrews1m@com.com', 'Jonathan', 'Andrews');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('neque', 793, '606863490', 'rwhite1n@wp.com', 'Robin', 'White');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('feugiat non pretium', 435, '490792527', 'kwarren1o@ameblo.jp', 'Kathryn', 'Warren');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ut nulla sed', 958, '273744575', 'mwoods1p@google.ru', 'Martha', 'Woods');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('risus semper', 168, '830802580', 'mray1q@amazon.co.jp', 'Margaret', 'Ray');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nam ultrices libero', 287, '083883101', 'mgarrett1r@scientificamerican.com', 'Mary', 'Garrett');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('rhoncus mauris enim', 206, '320138853', 'tcooper1s@usa.gov', 'Timothy', 'Cooper');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('morbi', 778, '817852934', 'tduncan1t@ox.ac.uk', 'Terry', 'Duncan');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla justo', 603, '283438642', 'bstevens1u@theglobeandmail.com', 'Betty', 'Stevens');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('rutrum rutrum neque', 534, '288483727', 'sallen1v@hc360.com', 'Sandra', 'Allen');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('consequat', 960, '349077277', 'gharper1w@mapy.cz', 'Gerald', 'Harper');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pede malesuada in', 545, '786100991', 'cmorgan1x@mlb.com', 'Carlos', 'Morgan');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('purus phasellus in', 104, '644448968', 'mblack1y@miitbeian.gov.cn', 'Matthew', 'Black');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet', 549, '427356018', 'psimmons1z@yahoo.com', 'Phillip', 'Simmons');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('maecenas rhoncus', 1, '313809644', 'ssmith20@biglobe.ne.jp', 'Sara', 'Smith');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('massa', 61, '938405957', 'rlawson21@guardian.co.uk', 'Rachel', 'Lawson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('integer', 483, '022899281', 'jfields22@over-blog.com', 'Jeremy', 'Fields');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('aliquet', 221, '998255263', 'kflores23@epa.gov', 'Keith', 'Flores');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nunc commodo', 902, '493648494', 'kmoore24@pbs.org', 'Kimberly', 'Moore');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet cursus id', 29, '403481168', 'pbaker25@about.com', 'Paula', 'Baker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in purus', 220, '662939212', 'manderson26@zimbio.com', 'Martha', 'Anderson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('aenean', 866, '604070823', 'psnyder27@twitpic.com', 'Patrick', 'Snyder');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('convallis eget', 846, '697528919', 'fpeters28@seesaa.net', 'Frances', 'Peters');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam fringilla', 250, '236025212', 'jhanson29@vinaora.com', 'Jimmy', 'Hanson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('risus', 192, '953432985', 'rmurphy2a@archive.org', 'Raymond', 'Murphy');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('curabitur', 505, '054253600', 'rmills2b@globo.com', 'Robert', 'Mills');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('neque aenean', 972, '063282679', 'rrice2c@ustream.tv', 'Raymond', 'Rice');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nec sem duis', 956, '881564110', 'dduncan2d@noaa.gov', 'Deborah', 'Duncan');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet consectetuer', 997, '120551527', 'wschmidt2e@mashable.com', 'Willie', 'Schmidt');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('a libero', 266, '640218493', 'pdixon2f@skype.com', 'Phyllis', 'Dixon');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ut', 227, '039591459', 'jhenry2g@trellian.com', 'James', 'Henry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eu est congue', 366, '947308328', 'kmurray2h@usatoday.com', 'Kathleen', 'Murray');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum sit', 456, '105121061', 'dvasquez2i@dell.com', 'Douglas', 'Vasquez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('proin leo odio', 221, '964407754', 'wholmes2j@yelp.com', 'William', 'Holmes');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('turpis nec', 526, '637934833', 'jkennedy2k@mail.ru', 'Jacqueline', 'Kennedy');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('semper est quam', 622, '777875795', 'erivera2l@netlog.com', 'Emily', 'Rivera');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('placerat', 676, '219381680', 'mmurphy2m@github.com', 'Margaret', 'Murphy');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('elementum', 584, '243678247', 'lmurphy2n@slashdot.org', 'Louis', 'Murphy');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('varius nulla facilisi', 629, '619312599', 'sporter2o@blog.com', 'Sean', 'Porter');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('morbi non quam', 329, '230162022', 'lbowman2p@ocn.ne.jp', 'Lawrence', 'Bowman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('posuere nonummy integer', 675, '537174970', 'hwillis2q@ca.gov', 'Heather', 'Willis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('tincidunt', 348, '266968588', 'acruz2r@facebook.com', 'Arthur', 'Cruz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('volutpat convallis morbi', 949, '656513966', 'hchapman2s@house.gov', 'Helen', 'Chapman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet nunc viverra', 837, '603179747', 'awood2t@unesco.org', 'Anna', 'Wood');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eget elit sodales', 414, '149366278', 'bfoster2u@comsenz.com', 'Bobby', 'Foster');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('duis mattis', 574, '371118229', 'dharper2v@pbs.org', 'Douglas', 'Harper');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum', 740, '789502003', 'blittle2w@nsw.gov.au', 'Barbara', 'Little');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lectus pellentesque', 841, '530343301', 'amcdonald2x@army.mil', 'Anne', 'Mcdonald');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('montes nascetur', 472, '862447805', 'rmontgomery2y@github.com', 'Rachel', 'Montgomery');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet justo', 450, '389768764', 'jromero2z@biglobe.ne.jp', 'Jesse', 'Romero');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lobortis', 375, '529864796', 'cpowell30@privacy.gov.au', 'Catherine', 'Powell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('porttitor', 813, '366472428', 'mpatterson31@freewebs.com', 'Martin', 'Patterson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('a suscipit nulla', 982, '380859068', 'sramirez32@guardian.co.uk', 'Susan', 'Ramirez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pellentesque quisque', 123, '198837062', 'jhenry33@indiegogo.com', 'Juan', 'Henry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ridiculus mus etiam', 717, '437851789', 'ehudson34@4shared.com', 'Evelyn', 'Hudson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('non mauris morbi', 629, '711934530', 'dlynch35@liveinternet.ru', 'Denise', 'Lynch');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('tempus', 877, '704890316', 'rhill36@zimbio.com', 'Rose', 'Hill');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('turpis elementum', 129, '511776470', 'mfrazier37@ovh.net', 'Marie', 'Frazier');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mattis odio donec', 826, '354605133', 'sboyd38@nymag.com', 'Sandra', 'Boyd');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('scelerisque mauris', 104, '730540700', 'rwheeler39@java.com', 'Robin', 'Wheeler');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('potenti in', 435, '126811268', 'whernandez3a@google.com', 'Wayne', 'Hernandez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('montes nascetur ridiculus', 727, '034299472', 'rhawkins3b@qq.com', 'Robin', 'Hawkins');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lacus', 663, '938953664', 'dparker3c@ifeng.com', 'Diane', 'Parker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('curabitur convallis duis', 629, '632233761', 'pharris3d@rambler.ru', 'Philip', 'Harris');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('convallis', 58, '905651034', 'tchavez3e@webmd.com', 'Theresa', 'Chavez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('suscipit ligula in', 839, '047818762', 'ccruz3f@dailymail.co.uk', 'Cheryl', 'Cruz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('leo maecenas pulvinar', 743, '788823528', 'rbutler3g@google.com', 'Robin', 'Butler');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('massa tempor convallis', 743, '912209722', 'jmyers3h@berkeley.edu', 'Jeffrey', 'Myers');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('primis in', 831, '193224948', 'slee3i@netvibes.com', 'Sarah', 'Lee');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nec condimentum neque', 240, '364174807', 'kblack3j@comcast.net', 'Kelly', 'Black');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pede', 28, '124670125', 'rgonzales3k@posterous.com', 'Rebecca', 'Gonzales');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sed', 61, '714321049', 'phughes3l@cpanel.net', 'Philip', 'Hughes');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('donec ut mauris', 483, '983877285', 'prodriguez3m@nbcnews.com', 'Paula', 'Rodriguez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mollis', 673, '799918105', 'rpierce3n@blog.com', 'Ronald', 'Pierce');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lectus in est', 133, '547710407', 'cdiaz3o@odnoklassniki.ru', 'Cheryl', 'Diaz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sodales', 466, '403342284', 'vyoung3p@indiatimes.com', 'Virginia', 'Young');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eu', 399, '376338678', 'egarcia3q@chicagotribune.com', 'Elizabeth', 'Garcia');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eu est congue', 372, '328167867', 'rkelley3r@tuttocitta.it', 'Rebecca', 'Kelley');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('justo morbi', 447, '691174821', 'aowens3s@nsw.gov.au', 'Anna', 'Owens');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('tincidunt eu felis', 638, '078593641', 'btaylor3t@sogou.com', 'Brenda', 'Taylor');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('malesuada in imperdiet', 932, '378396847', 'lshaw3u@bravesites.com', 'Laura', 'Shaw');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('elementum', 331, '198435442', 'sschmidt3v@columbia.edu', 'Shawn', 'Schmidt');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nunc viverra', 967, '296084792', 'ccook3w@amazonaws.com', 'Chris', 'Cook');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mattis pulvinar', 700, '136047479', 'tgrant3x@comcast.net', 'Tammy', 'Grant');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('rhoncus mauris', 994, '062591679', 'vowens3y@senate.gov', 'Victor', 'Owens');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mauris', 843, '214580147', 'jwatkins3z@woothemes.com', 'Joan', 'Watkins');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla neque libero', 224, '059498080', 'jrichards40@zimbio.com', 'Jeremy', 'Richards');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('accumsan', 954, '827918404', 'bwright41@domainmarket.com', 'Billy', 'Wright');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in ante', 362, '360641264', 'jreyes42@slideshare.net', 'John', 'Reyes');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('cubilia curae duis', 857, '499071968', 'tflores43@microsoft.com', 'Thomas', 'Flores');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('natoque penatibus et', 785, '543777548', 'sgrant44@sfgate.com', 'Steven', 'Grant');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('purus eu', 635, '320347004', 'jnichols45@nba.com', 'Jose', 'Nichols');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('non', 559, '426305007', 'mgriffin46@ebay.com', 'Marie', 'Griffin');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('curabitur', 628, '107795716', 'pwood47@columbia.edu', 'Philip', 'Wood');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dolor sit amet', 36, '701236967', 'aperry48@ocn.ne.jp', 'Ann', 'Perry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('congue', 788, '672036661', 'badams49@theguardian.com', 'Bonnie', 'Adams');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('rhoncus', 275, '857559078', 'asmith4a@t-online.de', 'Ashley', 'Smith');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet', 62, '475866630', 'warnold4b@blogspot.com', 'William', 'Arnold');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('velit vivamus vel', 139, '845993930', 'jpalmer4c@flickr.com', 'Judith', 'Palmer');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('convallis', 765, '428572645', 'ffields4d@google.es', 'Fred', 'Fields');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla', 304, '227897527', 'ablack4e@netvibes.com', 'Ashley', 'Black');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quis', 144, '124927121', 'twoods4f@biblegateway.com', 'Teresa', 'Woods');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('non velit donec', 108, '615976210', 'tmedina4g@technorati.com', 'Tina', 'Medina');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('at', 326, '418650348', 'llewis4h@narod.ru', 'Linda', 'Lewis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('duis aliquam convallis', 210, '216382543', 'pray4i@nydailynews.com', 'Patricia', 'Ray');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('potenti nullam', 107, '575522139', 'jreed4j@japanpost.jp', 'Jesse', 'Reed');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('elit ac', 992, '254776066', 'sbaker4k@bbc.co.uk', 'Shawn', 'Baker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ullamcorper', 26, '309328411', 'pward4l@deviantart.com', 'Paula', 'Ward');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('luctus nec molestie', 772, '454920338', 'tsnyder4m@bravesites.com', 'Teresa', 'Snyder');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sapien', 777, '939602798', 'kcruz4n@cyberchimps.com', 'Kathleen', 'Cruz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum', 91, '008981659', 'aburke4o@yolasite.com', 'Antonio', 'Burke');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lorem integer', 340, '486071413', 'lallen4p@weather.com', 'Linda', 'Allen');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('at turpis a', 208, '089909103', 'vpayne4q@usa.gov', 'Virginia', 'Payne');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('cursus', 552, '719125244', 'cbrooks4r@themeforest.net', 'Cheryl', 'Brooks');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla', 932, '420077345', 'dschmidt4s@businessweek.com', 'David', 'Schmidt');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum sagittis', 574, '868990900', 'adean4t@weibo.com', 'Andrew', 'Dean');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('justo lacinia', 864, '415330804', 'rhawkins4u@sakura.ne.jp', 'Robert', 'Hawkins');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet justo', 297, '120074064', 'jmccoy4v@berkeley.edu', 'John', 'Mccoy');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ornare consequat lectus', 751, '270861852', 'dcole4w@latimes.com', 'Doris', 'Cole');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eros', 941, '817989158', 'epalmer4x@cbslocal.com', 'Eugene', 'Palmer');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ultrices', 174, '388359114', 'dlawrence4y@parallels.com', 'Dorothy', 'Lawrence');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('primis', 266, '044205342', 'ahansen4z@mysql.com', 'Amanda', 'Hansen');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('semper', 759, '563210617', 'bgreen50@washingtonpost.com', 'Bobby', 'Green');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet', 202, '742212902', 'rgarza51@webnode.com', 'Rachel', 'Garza');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('luctus', 40, '440844098', 'greid52@cocolog-nifty.com', 'Gerald', 'Reid');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('suspendisse accumsan tortor', 505, '908504549', 'rgeorge53@state.gov', 'Richard', 'George');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet sapien', 782, '336040687', 'rriley54@auda.org.au', 'Randy', 'Riley');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quisque', 840, '997242492', 'hduncan55@hugedomains.com', 'Howard', 'Duncan');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ac consequat metus', 730, '453648414', 'jray56@salon.com', 'Jason', 'Ray');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('interdum venenatis', 666, '333844595', 'pmeyer57@addtoany.com', 'Paul', 'Meyer');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('morbi a ipsum', 83, '325080757', 'cphillips58@accuweather.com', 'Charles', 'Phillips');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('felis ut', 904, '056261954', 'hhawkins59@typepad.com', 'Howard', 'Hawkins');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vehicula', 392, '786429542', 'rlittle5a@wisc.edu', 'Richard', 'Little');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('aliquam', 884, '634281169', 'cstanley5b@shutterfly.com', 'Carol', 'Stanley');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('justo in hac', 312, '741899933', 'hcampbell5c@nhs.uk', 'Harry', 'Campbell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vel', 716, '610934348', 'jfox5d@ed.gov', 'Janet', 'Fox');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nisl nunc nisl', 246, '277546114', 'rortiz5e@twitter.com', 'Ryan', 'Ortiz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('duis ac nibh', 680, '171591667', 'cgreen5f@t.co', 'Chris', 'Green');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quisque id justo', 421, '226180747', 'rrobertson5g@mac.com', 'Ronald', 'Robertson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('interdum', 877, '977352876', 'dbradley5h@shutterfly.com', 'Denise', 'Bradley');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sed interdum', 97, '906680872', 'afrazier5i@adobe.com', 'Andrew', 'Frazier');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ipsum', 348, '408816844', 'kcox5j@bravesites.com', 'Kimberly', 'Cox');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('molestie nibh', 521, '330085814', 'dstanley5k@hexun.com', 'Daniel', 'Stanley');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('tincidunt eu felis', 21, '115076993', 'dmatthews5l@epa.gov', 'Donald', 'Matthews');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('parturient', 75, '889048505', 'msims5m@meetup.com', 'Martha', 'Sims');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('duis', 518, '722415349', 'jbrown5n@hubpages.com', 'Jose', 'Brown');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dis parturient montes', 903, '434746640', 'bstevens5o@netvibes.com', 'Brenda', 'Stevens');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in purus', 804, '169370211', 'cgarcia5p@cdc.gov', 'Charles', 'Garcia');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('interdum mauris non', 534, '033083076', 'lgeorge5q@ed.gov', 'Lillian', 'George');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum sit amet', 294, '589852096', 'nhunter5r@ucoz.com', 'Norma', 'Hunter');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('adipiscing', 985, '472628149', 'hfisher5s@sourceforge.net', 'Henry', 'Fisher');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('condimentum', 573, '497231826', 'rwest5t@accuweather.com', 'Robert', 'West');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam', 668, '309116347', 'kbowman5u@fema.gov', 'Karen', 'Bowman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('odio cras', 608, '816068428', 'bcole5v@wp.com', 'Brian', 'Cole');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('magna', 888, '398623338', 'bstephens5w@umn.edu', 'Bruce', 'Stephens');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('a nibh in', 974, '470678891', 'dsmith5x@gmpg.org', 'Daniel', 'Smith');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('at lorem integer', 778, '764388443', 'wcollins5y@zimbio.com', 'Wanda', 'Collins');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('justo etiam pretium', 431, '826550258', 'jarmstrong5z@amazonaws.com', 'Jesse', 'Armstrong');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('leo maecenas pulvinar', 707, '957020768', 'rwagner60@bing.com', 'Rose', 'Wagner');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('leo', 370, '223411535', 'pbryant61@sina.com.cn', 'Paula', 'Bryant');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('arcu adipiscing', 893, '367382537', 'rhart62@patch.com', 'Roy', 'Hart');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla', 686, '811684228', 'ayoung63@weather.com', 'Anna', 'Young');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vulputate ut ultrices', 194, '035890026', 'bramirez64@amazon.de', 'Brandon', 'Ramirez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pretium nisl', 916, '446378691', 'mgeorge65@devhub.com', 'Maria', 'George');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pharetra magna ac', 192, '423762382', 'afowler66@1688.com', 'Antonio', 'Fowler');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in', 764, '378457024', 'lchapman67@shop-pro.jp', 'Larry', 'Chapman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vulputate ut', 677, '988679205', 'jmason68@facebook.com', 'Julia', 'Mason');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('amet turpis', 118, '810823070', 'mbrown69@tiny.cc', 'Martin', 'Brown');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum velit id', 482, '975087998', 'celliott6a@yahoo.com', 'Carolyn', 'Elliott');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet erat', 194, '302150008', 'mknight6b@ucla.edu', 'Mark', 'Knight');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('velit', 355, '919891600', 'estewart6c@tiny.cc', 'Earl', 'Stewart');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mauris', 559, '815275530', 'jhenderson6d@china.com.cn', 'Jeremy', 'Henderson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('curabitur', 987, '664663616', 'nlong6e@army.mil', 'Nicholas', 'Long');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in', 533, '651519673', 'sramos6f@istockphoto.com', 'Sharon', 'Ramos');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('scelerisque', 709, '057109392', 'jdixon6g@imdb.com', 'Jason', 'Dixon');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in leo', 231, '234549774', 'pmarshall6h@printfriendly.com', 'Paul', 'Marshall');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla eget eros', 215, '219065084', 'eross6i@pagesperso-orange.fr', 'Earl', 'Ross');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('consequat', 120, '472044390', 'clittle6j@sphinn.com', 'Clarence', 'Little');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('vestibulum rutrum', 555, '372288795', 'shudson6k@domainmarket.com', 'Sara', 'Hudson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('elit ac nulla', 48, '182791925', 'bgibson6l@comsenz.com', 'Bobby', 'Gibson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sapien cum sociis', 178, '007695351', 'kpatterson6m@state.tx.us', 'Kathy', 'Patterson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('phasellus', 56, '938989641', 'dhanson6n@techcrunch.com', 'David', 'Hanson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('volutpat', 566, '618722412', 'hmendoza6o@macromedia.com', 'Harry', 'Mendoza');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('odio consequat varius', 691, '109871489', 'bboyd6p@china.com.cn', 'Bonnie', 'Boyd');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('non interdum', 798, '690691049', 'gbarnes6q@washingtonpost.com', 'Gloria', 'Barnes');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('consequat nulla', 373, '106657445', 'cwilliams6r@shareasale.com', 'Catherine', 'Williams');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mauris eget massa', 274, '197101730', 'lfields6s@tmall.com', 'Lori', 'Fields');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('hac habitasse', 206, '563056489', 'bhansen6t@sitemeter.com', 'Billy', 'Hansen');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('libero rutrum ac', 561, '545222424', 'khoward6u@wp.com', 'Kenneth', 'Howard');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('praesent blandit nam', 50, '629604587', 'ljacobs6v@gmpg.org', 'Linda', 'Jacobs');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('id luctus', 848, '903593423', 'bcampbell6w@cocolog-nifty.com', 'Brian', 'Campbell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('consectetuer adipiscing', 267, '886655088', 'mshaw6x@weather.com', 'Melissa', 'Shaw');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('habitasse', 61, '325242596', 'amontgomery6y@360.cn', 'Anna', 'Montgomery');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('et', 101, '085382813', 'tgardner6z@kickstarter.com', 'Tina', 'Gardner');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('penatibus et', 694, '228081348', 'bthomas70@artisteer.com', 'Brenda', 'Thomas');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('gravida', 427, '289161415', 'egarza71@webmd.com', 'Edward', 'Garza');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla', 847, '297442993', 'dmedina72@comsenz.com', 'Denise', 'Medina');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dictumst morbi', 730, '725392720', 'kwillis73@state.tx.us', 'Keith', 'Willis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet consectetuer', 25, '819859872', 'wwood74@smugmug.com', 'William', 'Wood');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('accumsan odio', 62, '871535751', 'kbryant75@live.com', 'Kelly', 'Bryant');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in hac', 791, '434768600', 'awright76@jalbum.net', 'Andrew', 'Wright');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sapien varius', 541, '114931398', 'scrawford77@ycombinator.com', 'Steven', 'Crawford');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('eu', 265, '669215070', 'smills78@simplemachines.org', 'Sean', 'Mills');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('et ultrices posuere', 622, '533860789', 'dhansen79@seesaa.net', 'Dorothy', 'Hansen');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('molestie', 17, '232732512', 'ccampbell7a@feedburner.com', 'Cynthia', 'Campbell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lorem integer', 767, '974364131', 'ahenry7b@instagram.com', 'Anna', 'Henry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dolor vel est', 763, '984371181', 'ediaz7c@java.com', 'Ernest', 'Diaz');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('est et', 196, '342688178', 'wallen7d@economist.com', 'Wayne', 'Allen');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dis parturient', 985, '879203461', 'pmatthews7e@issuu.com', 'Peter', 'Matthews');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quis justo maecenas', 811, '021377015', 'dwilliams7f@google.com.br', 'Diana', 'Williams');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('primis', 331, '597442787', 'jperez7g@ed.gov', 'Jimmy', 'Perez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('consequat', 357, '249998702', 'cturner7h@goo.gl', 'Cheryl', 'Turner');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('donec ut mauris', 220, '433885976', 'jmartinez7i@oracle.com', 'Joe', 'Martinez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('elementum', 524, '841047126', 'dlawrence7j@chicagotribune.com', 'Denise', 'Lawrence');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('lacinia', 690, '112560862', 'phenry7k@mtv.com', 'Paula', 'Henry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('molestie', 13, '021466821', 'pfields7l@google.com.br', 'Pamela', 'Fields');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in imperdiet et', 849, '239384476', 'jgreen7m@csmonitor.com', 'Julie', 'Green');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('posuere', 117, '269020551', 'apayne7n@bloomberg.com', 'Arthur', 'Payne');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ac lobortis', 90, '292612905', 'sblack7o@virginia.edu', 'Sandra', 'Black');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('et eros', 408, '125499676', 'hlewis7p@dailymotion.com', 'Harry', 'Lewis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('curae', 149, '844086666', 'jfreeman7q@yolasite.com', 'Janice', 'Freeman');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('odio odio elementum', 341, '584875748', 'djohnston7r@tuttocitta.it', 'Douglas', 'Johnston');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('at velit', 328, '755750707', 'bbailey7s@google.com', 'Brian', 'Bailey');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sit amet eros', 640, '727826835', 'mnichols7t@netvibes.com', 'Maria', 'Nichols');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('pulvinar sed nisl', 562, '667084721', 'hwalker7u@hatena.ne.jp', 'Harold', 'Walker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nascetur', 738, '899518385', 'cfranklin7v@chronoengine.com', 'Carol', 'Franklin');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('nulla eget eros', 617, '715361980', 'kkelley7w@discovery.com', 'Kathy', 'Kelley');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('duis bibendum', 544, '259544939', 'dferguson7x@livejournal.com', 'Dorothy', 'Ferguson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sed nisl nunc', 707, '393567216', 'chenry7y@linkedin.com', 'Christopher', 'Henry');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('mi pede', 512, '047502716', 'hbennett7z@japanpost.jp', 'Harry', 'Bennett');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('curae nulla dapibus', 314, '603210559', 'wwillis80@apple.com', 'Willie', 'Willis');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('in consequat ut', 674, '386531282', 'ajohnson81@deliciousdays.com', 'Aaron', 'Johnson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('orci pede', 431, '829910574', 'kphillips82@berkeley.edu', 'Kimberly', 'Phillips');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ligula pellentesque', 961, '859534667', 'bmartinez83@networkadvertising.org', 'Billy', 'Martinez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('penatibus', 303, '914107000', 'ifrazier84@freewebs.com', 'Irene', 'Frazier');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('porttitor', 495, '906837462', 'chernandez85@nyu.edu', 'Clarence', 'Hernandez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('ac', 568, '898849620', 'sbell86@abc.net.au', 'Scott', 'Bell');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam a', 246, '120274461', 'arobertson87@msn.com', 'Anne', 'Robertson');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('faucibus', 407, '567886749', 'sromero88@ovh.net', 'Shirley', 'Romero');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('dui luctus rutrum', 130, '172477818', 'amartinez89@skyrock.com', 'Anthony', 'Martinez');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('sapien sapien non', 215, '158749694', 'mtucker8a@4shared.com', 'Mary', 'Tucker');
insert into client (companyName, eventID, phoneNum, email, liaisonFName, liaisonLName) values ('quam sapien', 505, '092636375', 'mreid8b@nps.gov', 'Matthew', 'Reid');
